"""
Mapeo de símbolos de Binance a nombres completos de monedas.
Este diccionario se usa para mostrar nombres legibles en las alertas de Telegram.
"""

COIN_NAMES = {
    # Bitcoin
    "BTC": "Bitcoin",
    "BTCUSDT": "Bitcoin",
    
    # Altcoins populares
    "ETH": "Ethereum",
    "ETHUSDT": "Ethereum",
    "BNB": "Binance Coin",
    "BNBUSDT": "Binance Coin",
    "SOL": "Solana",
    "SOLUSDT": "Solana",
    "ADA": "Cardano",
    "ADAUSDT": "Cardano",
    "AVAX": "Avalanche",
    "AVAXUSDT": "Avalanche",
    "DOT": "Polkadot",
    "DOTUSDT": "Polkadot",
    "NEAR": "NEAR Protocol",
    "NEARUSDT": "NEAR Protocol",
    "ATOM": "Cosmos",
    "ATOMUSDT": "Cosmos",
    "FTM": "Fantom",
    "FTMUSDT": "Fantom",
    "ALGO": "Algorand",
    "ALGOUSDT": "Algorand",
    "ICP": "Internet Computer",
    "ICPUSDT": "Internet Computer",
    "HBAR": "Hedera",
    "HBARUSDT": "Hedera",
    "EGLD": "MultiversX",
    "EGLDUSDT": "MultiversX",
    "FLOW": "Flow",
    "FLOWUSDT": "Flow",
    "ROSE": "Oasis Network",
    "ROSEUSDT": "Oasis Network",
    
    # DeFi
    "UNI": "Uniswap",
    "UNIUSDT": "Uniswap",
    "AAVE": "Aave",
    "AAVEUSDT": "Aave",
    "MKR": "Maker",
    "MKRUSDT": "Maker",
    "COMP": "Compound",
    "COMPUSDT": "Compound",
    "SNX": "Synthetix",
    "SNXUSDT": "Synthetix",
    "CRV": "Curve DAO",
    "CRVUSDT": "Curve DAO",
    "SUSHI": "SushiSwap",
    "SUSHIUSDT": "SushiSwap",
    "YFI": "yearn.finance",
    "YFIUSDT": "yearn.finance",
    "BAL": "Balancer",
    "BALUSDT": "Balancer",
    "1INCH": "1inch Network",
    "1INCHUSDT": "1inch Network",
    "LDO": "Lido DAO",
    "LDOUSDT": "Lido DAO",
    "RPL": "Rocket Pool",
    "RPLUSDT": "Rocket Pool",
    "FXS": "Frax Share",
    "FXSUSDT": "Frax Share",
    "PENDLE": "Pendle",
    "PENDLEUSDT": "Pendle",
    "RDNT": "Radiant Capital",
    "RDNTUSDT": "Radiant Capital",
    
    # Layer 2
    "MATIC": "Polygon",
    "MATICUSDT": "Polygon",
    "ARB": "Arbitrum",
    "ARBUSDT": "Arbitrum",
    "OP": "Optimism",
    "OPUSDT": "Optimism",
    "IMX": "Immutable X",
    "IMXUSDT": "Immutable X",
    "LRC": "Loopring",
    "LRCUSDT": "Loopring",
    "SKL": "SKALE",
    "SKLUSDT": "SKALE",
    "CELR": "Celer Network",
    "CELRUSDT": "Celer Network",
    "OMG": "OMG Network",
    "OMGUSDT": "OMG Network",
    "ZKS": "ZKsync",
    "ZKSUSDT": "ZKsync",
    "STRK": "StarkNet",
    "STRKUSDT": "StarkNet",
    "METIS": "Metis",
    "METISUSDT": "Metis",
    "BOBA": "Boba Network",
    "BOBAUSDT": "Boba Network",
    "COTI": "COTI",
    "COTIUSDT": "COTI",
    "MINA": "Mina Protocol",
    "MINAUSDT": "Mina Protocol",
    "AZERO": "Aleph Zero",
    "AZEROUSDT": "Aleph Zero",
    
    # AI
    "FET": "Fetch.ai",
    "FETUSDT": "Fetch.ai",
    "AGIX": "SingularityNET",
    "AGIXUSDT": "SingularityNET",
    "OCEAN": "Ocean Protocol",
    "OCEANUSDT": "Ocean Protocol",
    "NMR": "Numeraire",
    "NMRUSDT": "Numeraire",
    "CTXC": "Cortex",
    "CTXCUSDT": "Cortex",
    "MDT": "Measurable Data Token",
    "MDTUSDT": "Measurable Data Token",
    "RLC": "iExec RLC",
    "RLCUSDT": "iExec RLC",
    "DATA": "Streamr",
    "DATAUSDT": "Streamr",
    "VIDT": "VIDT DAO",
    "VIDTUSDT": "VIDT DAO",
    "PHB": "Phoenix",
    "PHBUSDT": "Phoenix",
    "NKN": "NKN",
    "NKNUSDT": "NKN",
    "ARKM": "Arkham",
    "ARKMUSDT": "Arkham",
    "WLD": "Worldcoin",
    "WLDUSDT": "Worldcoin",
    "TAO": "Bittensor",
    "TAOUSDT": "Bittensor",
    "PRIME": "Echelon Prime",
    "PRIMEUSDT": "Echelon Prime",
    
    # Meme
    "DOGE": "Dogecoin",
    "DOGEUSDT": "Dogecoin",
    "SHIB": "Shiba Inu",
    "SHIBUSDT": "Shiba Inu",
    "PEPE": "Pepe",
    "PEPEUSDT": "Pepe",
    "FLOKI": "Floki",
    "FLOKIUSDT": "Floki",
    "BONK": "Bonk",
    "BONKUSDT": "Bonk",
    "WIF": "dogwifhat",
    "WIFUSDT": "dogwifhat",
    "MEME": "Memecoin",
    "MEMEUSDT": "Memecoin",
    "PEOPLE": "ConstitutionDAO",
    "PEOPLEUSDT": "ConstitutionDAO",
    "TURBO": "Turbo",
    "TURBOUSDT": "Turbo",
    "BABYDOGE": "Baby Doge Coin",
    "BABYDOGEUSDT": "Baby Doge Coin",
    "COQ": "Coq Inu",
    "COQUSDT": "Coq Inu",
    "MYRO": "Myro",
    "MYROUSDT": "Myro",
    "WEN": "Wen",
    "WENUSDT": "Wen",
    "SLERF": "Slerf",
    "SLERFUSDT": "Slerf",
    "SAMO": "Samoyedcoin",
    "SAMOUSDT": "Samoyedcoin",
    
    # Gaming
    "AXS": "Axie Infinity",
    "AXSUSDT": "Axie Infinity",
    "SAND": "The Sandbox",
    "SANDUSDT": "The Sandbox",
    "MANA": "Decentraland",
    "MANAUSDT": "Decentraland",
    "ENJ": "Enjin Coin",
    "ENJUSDT": "Enjin Coin",
    "GALA": "Gala",
    "GALAUSDT": "Gala",
    "ILV": "Illuvium",
    "ILVUSDT": "Illuvium",
    "ALICE": "My Neighbor Alice",
    "ALICEUSDT": "My Neighbor Alice",
    "TLM": "Alien Worlds",
    "TLMUSDT": "Alien Worlds",
    "DAR": "Mines of Dalarnia",
    "DARUSDT": "Mines of Dalarnia",
    "VOXEL": "Voxies",
    "VOXELUSDT": "Voxies",
    "MC": "Merit Circle",
    "MCUSDT": "Merit Circle",
    "PYR": "Vulcan Forged",
    "PYRUSDT": "Vulcan Forged",
    "YGG": "Yield Guild Games",
    "YGGUSDT": "Yield Guild Games",
    "BIGTIME": "Big Time",
    "BIGTIMEUSDT": "Big Time",
    "NAKA": "Nakamoto Games",
    "NAKAUSDT": "Nakamoto Games",
    
    # Oracle
    "LINK": "Chainlink",
    "LINKUSDT": "Chainlink",
    "BAND": "Band Protocol",
    "BANDUSDT": "Band Protocol",
    "TRB": "Tellor",
    "TRBUSDT": "Tellor",
    "API3": "API3",
    "API3USDT": "API3",
    "UMA": "UMA",
    "UMAUSDT": "UMA",
    "DIA": "DIA",
    "DIAUSDT": "DIA",
    "PYTH": "Pyth Network",
    "PYTHUSDT": "Pyth Network",
    
    # Storage
    "FIL": "Filecoin",
    "FILUSDT": "Filecoin",
    "AR": "Arweave",
    "ARUSDT": "Arweave",
    "STORJ": "Storj",
    "STORJUSDT": "Storj",
    "SC": "Siacoin",
    "SCUSDT": "Siacoin",
    "ANKR": "Ankr",
    "ANKRUSDT": "Ankr",
    "HOT": "Holo",
    "HOTUSDT": "Holo",
    "BLZ": "Bluzelle",
    "BLZUSDT": "Bluzelle",
    
    # RWA
    "CFG": "Centrifuge",
    "CFGUSDT": "Centrifuge",
    "TRU": "TrueFi",
    "TRUUSDT": "TrueFi",
    "RIO": "Realio Network",
    "RIOUSDT": "Realio Network",
    "ONDO": "Ondo Finance",
    "ONDOUSDT": "Ondo Finance",
    "TOKEN": "TokenFi",
    "TOKENUSDT": "TokenFi",
    
    # Otros
    "XRP": "Ripple",
    "XRPUSDT": "Ripple",
    "LTC": "Litecoin",
    "LTCUSDT": "Litecoin",
    "BCH": "Bitcoin Cash",
    "BCHUSDT": "Bitcoin Cash",
    "XLM": "Stellar",
    "XLMUSDT": "Stellar",
    "TRX": "TRON",
    "TRXUSDT": "TRON",
    "ETC": "Ethereum Classic",
    "ETCUSDT": "Ethereum Classic",
    "EOS": "EOS",
    "EOSUSDT": "EOS",
    "VET": "VeChain",
    "VETUSDT": "VeChain",
    "THETA": "Theta Network",
    "THETAUSDT": "Theta Network",
    "GRT": "The Graph",
    "GRTUSDT": "The Graph",
    "CHZ": "Chiliz",
    "CHZUSDT": "Chiliz",
    "ZIL": "Zilliqa",
    "ZILUSDT": "Zilliqa",
    "BAT": "Basic Attention Token",
    "BATUSDT": "Basic Attention Token",
    "ZRX": "0x",
    "ZRXUSDT": "0x",
    "KNC": "Kyber Network",
    "KNCUSDT": "Kyber Network",
    "DGB": "DigiByte",
    "DGBUSDT": "DigiByte",
    "DOCK": "Dock",
    "DOCKUSDT": "Dock",
    "FRONT": "Frontier",
    "FRONTUSDT": "Frontier",
    "VITE": "Vite",
    "VITEUSDT": "Vite",
    "DUSK": "Dusk Network",
    "DUSKUSDT": "Dusk Network",
    "PERL": "Perlin",
    "PERLUSDT": "Perlin",
    "REI": "REI Network",
    "REIUSDT": "REI Network",
    "STX": "Stacks",
    "STXUSDT": "Stacks",
    "CFX": "Conflux",
    "CFXUSDT": "Conflux",
    "KAS": "Kaspa",
    "KASUSDT": "Kaspa",
    "SEI": "Sei",
    "SEIUSDT": "Sei",
    "SUI": "Sui",
    "SUIUSDT": "Sui",
    "APT": "Aptos",
    "APTUSDT": "Aptos",
    "TIA": "Celestia",
    "TIAUSDT": "Celestia",
    "JTO": "Jito",
    "JTOUSDT": "Jito",
    "JUP": "Jupiter",
    "JUPUSDT": "Jupiter",
    "W": "Wormhole",
    "WUSDT": "Wormhole",
    "ENA": "Ethena",
    "ENAUSDT": "Ethena",
    "ETHFI": "Ether.fi",
    "ETHFIUSDT": "Ether.fi",
    "ALT": "AltLayer",
    "ALTUSDT": "AltLayer",
    "MANTA": "Manta Network",
    "MANTAUSDT": "Manta Network",
    "XAI": "Xai",
    "XAIUSDT": "Xai",
    "ACE": "Fusionist",
    "ACEUSDT": "Fusionist",
    "NFP": "NFPrompt",
    "NFPUSDT": "NFPrompt",
    "AI": "Sleepless AI",
    "AIUSDT": "Sleepless AI",
    "PORTAL": "Portal",
    "PORTALUSDT": "Portal",
    "RNDR": "Render Token",
    "RNDRUSDT": "Render Token",
    "INJ": "Injective",
    "INJUSDT": "Injective"
}

def get_full_name(symbol: str) -> str:
    """
    Retorna el nombre completo de una moneda a partir de su símbolo.
    Si no se encuentra, retorna el símbolo original.
    """
    # Eliminar USDT del final si está presente
    base_symbol = symbol.replace("USDT", "") if symbol.endswith("USDT") else symbol
    return COIN_NAMES.get(base_symbol, symbol)